#!/usr/bin/env bash
# nexus_start.sh — one-shot launcher for the Nexus peer enrollment flow.
# Runs the four steps in order: key check -> invite -> docker -> status.
# Usage:  ./scripts/nexus_start.sh
#         ./scripts/nexus_start.sh --skip-status
#         ./scripts/nexus_start.sh --dry-run
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/enroll_out"
KEY_FILE="${NETBIRD_KEY_FILE:-$HOME/.config/netbird/setup.key}"
PEER_COUNT="${NEXUS_PEER_COUNT:-47}"
DRY_RUN=0
SKIP_STATUS=0

for arg in "$@"; do
  case "$arg" in
    --dry-run)      DRY_RUN=1 ;;
    --skip-status)  SKIP_STATUS=1 ;;
    -h|--help)
      sed -n '2,8p' "$0" | sed 's/^# \?//'
      exit 0 ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

log()  { printf '\033[1;36m[nexus]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[nexus]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[nexus]\033[0m %s\n' "$*" >&2; exit 1; }

run() {
  if (( DRY_RUN )); then
    printf '  \033[2m$ %s\033[0m\n' "$*"
  else
    "$@"
  fi
}

# --- 1. Key check ----------------------------------------------------------
log "Step 1/4 — key check"
if [[ -n "${NETBIRD_SETUP_KEY:-}" ]]; then
  log "Key from env NETBIRD_SETUP_KEY (length ${#NETBIRD_SETUP_KEY})"
elif [[ -f "$KEY_FILE" ]]; then
  NETBIRD_SETUP_KEY="$(tr -d '[:space:]' < "$KEY_FILE")"
  log "Key loaded from $KEY_FILE"
else
  die "No key found. Set NETBIRD_SETUP_KEY or create $KEY_FILE (chmod 600)."
fi

# --- 2. Generate invite commands ------------------------------------------
log "Step 2/4 — generate ${PEER_COUNT} invite commands"
INVITE_SH="${OUT}/invite_commands.sh"
mkdir -p "$OUT"
{
  echo "#!/usr/bin/env bash"
  echo "# Auto-generated by nexus_start.sh — do not edit by hand."
  echo "set -euo pipefail"
  echo "KEY=\"${NETBIRD_SETUP_KEY}\""
  echo "for i in \$(seq -w 1 ${PEER_COUNT}); do"
  echo "  echo \"peer-\${i}: netbird up --setup-key \$KEY\""
  echo "done"
} > "$INVITE_SH"
chmod +x "$INVITE_SH"
log "Wrote $INVITE_SH"

# --- 3. Docker variant -----------------------------------------------------
log "Step 3/4 — docker enroll script"
DOCKER_SH="${OUT}/docker_enroll.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Auto-generated — dockerized netbird up for ${PEER_COUNT} peers."
  echo "set -euo pipefail"
  echo "KEY=\"${NETBIRD_SETUP_KEY}\""
  echo "for i in \$(seq -w 1 ${PEER_COUNT}); do"
  echo "  docker run -d --name nexus-peer-\${i} \\\n       --cap-add=NET_ADMIN --device /dev/net/tun \\\n       -e NB_SETUP_KEY=\"\$KEY\" \\\n       netbirdio/netbird:latest"
  echo "done"
} > "$DOCKER_SH"
chmod +x "$DOCKER_SH"
log "Wrote $DOCKER_SH"

# --- 4. Status check -------------------------------------------------------
if (( SKIP_STATUS == 0 )); then
  log "Step 4/4 — status check"
  STATUS_SH="${OUT}/check_status.sh"
  {
    echo "#!/usr/bin/env bash"
    echo "set -euo pipefail"
    echo "echo '--- netbird status ---'"
    echo "netbird status 2>/dev/null || echo 'netbird not installed or not connected'"
    echo "echo '--- peers (management API) ---'"
    echo "netbird status --detail 2>/dev/null | head -n 60 || true"
  } > "$STATUS_SH"
  chmod +x "$STATUS_SH"
  run bash "$STATUS_SH"
else
  log "Step 4/4 — skipped (--skip-status)"
fi

log "Done. Next: run $INVITE_SH on each host, or $DOCKER_SH."
log "Then: $OUT/check_status.sh"
